<Doctype html>
    <html lang="em">

    <head>
        <title>Html form</title>
    </head>

    <body>
        <h1>HTML Form</h1>

        <form method="POST" action="FORM ACCESS2.PHP">

            Name &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" placeholder="Enter your name" name="name">
            <br><br>

            Email &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" placeholder="Enter email" name="email">
            <br><br>

            Password &nbsp;
            <input type="password" placeholder="Enter password" name="password">
            <br><br>

            <input type="submit" placeholder="Submit"> <input type="Reset" placeholder="Reset">


        </form>
    </body>

    </html>